services:
  - type: web
    name: gitequity-backend
    runtime: docker
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: gitequity-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: gitequity-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: gitequity-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: gitequity-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gitequity-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: OAUTH2_REDIRECT_URI
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: gitequity-db
    databaseName: gitequity
    plan: free
